export const APP_UPDATE_OPENED_MENU = "APP_UPDATE_OPENED_MENU";
export const UPDATE_SHIRT_COLOR = "UPDATE_SHIRT_COLOR";
export const UPDATE_SHIRT_TYPE = "UPDATE_SHIRT_TYPE";
export const UPDATE_CANVAS = "UPDATE_CANVAS";
