export const APP_UPDATE_OPENED_MENU = 'APP_UPDATE_OPENED_MENU';
export const UPDATE_SHIRT_COLOR = 'UPDATE_SHIRT_COLOR';
export const UPDATE_SHIRT_TYPE = 'UPDATE_SHIRT_TYPE';
export const UPDATE_CANVAS = 'UPDATE_CANVAS';
export const UPDATE_OBJECTS_CANVAS = 'UPDATE_OBJECTS_CANVAS';
export const UPDATE_STATE_TEXT_OPTIONS = 'UPDATE_STATE_TEXT_OPTIONS';
export const UPDATE_VALUE_TEXT = 'UPDATE_VALUE_TEXT';
export const UPDATE_TEXT_OPTION_STATE = 'UPDATE_TEXT_OPTION_STATE';
